steps:
  # Build do Backend Django
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/included-backend:latest',
      '-f', 'included-backend/Dockerfile',
      'included-backend'
    ]
    id: 'build-backend'

  # Push das imagens para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA']
    waitFor: ['build-backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/included-backend:latest']
    waitFor: ['build-backend']

  # Executar migrações do Django (opcional)
  - name: 'gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA'
    entrypoint: python
    args: ['manage.py', 'migrate', '--noinput']
    env:
      - 'DJANGO_SETTINGS_MODULE=included_backend.settings'
      - 'DATABASE_URL=${_DATABASE_URL}'
    waitFor: ['build-backend']

  # Coletar arquivos estáticos
  - name: 'gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA'
    entrypoint: python
    args: ['manage.py', 'collectstatic', '--noinput']
    env:
      - 'DJANGO_SETTINGS_MODULE=included_backend.settings'
    waitFor: ['build-backend']

  # Deploy para Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'included-backend',
      '--image', 'gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '512Mi',
      '--cpu', '1',
      '--max-instances', '10',
      '--set-env-vars', 'DJANGO_SETTINGS_MODULE=included_backend.settings,DATABASE_URL=${_DATABASE_URL},SECRET_KEY=${_SECRET_KEY}'
    ]
    waitFor: ['build-backend']

# Configurações
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substituições
substitutions:
  _REGION: 'us-central1'
  _DATABASE_URL: 'postgresql://user:password@host:5432/database'
  _SECRET_KEY: 'your-secret-key-here'

# Imagens que serão criadas
images:
  - 'gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/included-backend:latest' 