# IncludED Platform - Cloud Build
steps:
  # Build Backend (clona na hora do build)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA',
      '-f', 'docker/Dockerfile.backend',
      '.'
    ]

  # Build Frontend (clona na hora do build)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/included-frontend:$COMMIT_SHA',
      '-f', 'docker/Dockerfile.frontend',
      '.'
    ]

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA']

  # Push Frontend Image  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/included-frontend:$COMMIT_SHA']

  # Deploy Backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'included-backend',
      '--image=gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA',
      '--region=us-central1',
      '--port=8000'
    ]

  # Deploy Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'included-frontend',
      '--image=gcr.io/$PROJECT_ID/included-frontend:$COMMIT_SHA',
      '--region=us-central1',
      '--port=80'
    ]

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
  
images:
  - gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/included-frontend:$COMMIT_SHA 