# IncludED Platform - Cloud Build
steps:
  # Clone repositórios direto (já conectados ao Cloud Build)  
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔄 Obtendo token de acesso..."
        TOKEN=$(gcloud auth print-access-token)
        
        echo "🔄 Clonando repositórios com autenticação..."
        git clone https://oauth2:$TOKEN@github.com/pixelpunk-included/included-backend.git included-backend
        git clone https://oauth2:$TOKEN@github.com/pixelpunk-included/included-frontend.git included-frontend
        
        echo "✅ Repositórios clonados com sucesso:"
        ls -la included-backend/ included-frontend/
    id: 'init-repos'

  # Build Backend (Django + PostgreSQL)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA',
      'included-backend'
    ]
    waitFor: ['init-repos']

  # Build Frontend (React + Vite + TypeScript)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/included-frontend:$COMMIT_SHA',
      '-f', 'included-frontend/Dockerfile.prod', 'included-frontend'
    ]
    waitFor: ['init-repos']

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA']

  # Push Frontend Image  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/included-frontend:$COMMIT_SHA']

  # Deploy Backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'included-backend',
      '--image=gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA',
      '--region=us-central1',
      '--port=8000'
    ]

  # Deploy Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'included-frontend',
      '--image=gcr.io/$PROJECT_ID/included-frontend:$COMMIT_SHA',
      '--region=us-central1',
      '--port=80'
    ]

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
  
images:
  - gcr.io/$PROJECT_ID/included-backend:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/included-frontend:$COMMIT_SHA 